### ISSUE TITLE
uint64_t timestamp representation - how to represent dates before the Unix Epoch?

### ISSUE THREAD

**Issue by herolover** [chronoxor/CppCommon#12]
May be it would be better to represent timestamp as signed integer(I mean `int64_t`) to allow using dates before the Unix Epoch.

Not sure if it's a common case, but it's definitely might happen. A probably real case - displaying very old monthly chart bars.

**Comment by chronoxor** [comment]
For old historical data it's better to chose different Epoch base and granularity. E.g. seconds since 0 AD
