### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by alejandro-colomar** [chronoxor/CppCommon#17]
Hi,

Could you please release a new version, when you feel it's more or less stable?
I'd like to package if for conan-center.

Thanks,

Alex

**Comment by chronoxor** [comment]
Please check updated version 1.0.1.0

**Comment by alejandro-colomar** [comment]
Would you mind helping here a bit?: <https://github.com/conan-io/conan-center-index/pull/5786>

Thank you very much!
