### ISSUE TITLE
Next release for conan

### ISSUE THREAD

**Issue by COM8** [chronoxor/CppCommon#19]
Since without #18 this lib does not compile with gcc >=10 or clang >=12 we need to create a new release of the conan package.
Because releases for conan are bound to git tags, there wont be one until you create a new one here.

Are there any plans for creating a new release tag soon?

**Comment by chronoxor** [comment]
Please check the new version 1.0.2.0
https://github.com/chronoxor/CppCommon/releases/tag/1.0.2.0

**Comment by COM8** [comment]
Awesome thanks!
