### ISSUE TITLE
build fails on musl based systems

### ISSUE THREAD

**Issue by karasz** [chronoxor/CppCommon#22]
On musl based systems we have three issues to overcome:

1. musl implements the POSIX standard strerror_r which returns an int not a pointer to a string which GNU specific
2. there is no pthread_yield in musl, only sched_yield. As far as I know on Linux pthread_yield will call sched_yield anyway
3. there is no backtrace.
After these issues are resolved CppCommon and hence FastBinaryEncoding will build and pass the tests
```
alpinebuilder:/usr/src/fbe/bin# ./fbe-tests 
===============================================================================
All tests passed (1003987 assertions in 45 test cases)
```

[Patch](https://github.com/karasz/CppCommon/commit/e4385e76f8de145d4cdc278232bddd59e67bc1e2)

I can provide a pull requests if the changes are deemed worthy.

**Comment by chronoxor** [comment]
Should be fixed. Please check
