### ISSUE TITLE
Test failure, test_system_stack_trace.cpp

### ISSUE THREAD

**Issue by search-git** [chronoxor/CppCommon#26]
1: /CppCommon/tests/test_system_stack_trace.cpp:36: FAILED:
1:   REQUIRE( frame.address != nullptr )
1: with expansion:

1:   nullptr != nullptr
1: test cases:   173 |   172 passed | 1 failed
1: assertions: 10877 | 10876 passed | 1 failed

**Comment by chronoxor** [comment]
Please try the most recent version of CppCommon. It is build on Ubutu, MacOS, Windows and all tests passed without errors:
![image](https://user-images.githubusercontent.com/4397805/145653886-1246cc00-77af-4818-8cfd-013f9da0ce30.png)
