### ISSUE TITLE
when open file with both read and write mode, Write and Flush will write read buffer.

### ISSUE THREAD

**Issue by yinkaisheng** [chronoxor/CppCommon#30]
```c++
CppCommon::Path path{ "CppApp.log.bak" };
CppCommon::File file(path);
file.Open(true, true);
if (file.IsFileOpened())
{
    char buf[1024]{};
    size_t read = file.Read(buf, CppCommon::countof(buf));
    auto offset = file.offset();
    CPPLOG_INFO("file offset: {}", offset);
    file.Write("@@@@@", 5);
    file.Flush();
    offset = file.offset();
    CPPLOG_INFO("file offset: {}", offset);
}
```
the output:
```
2023-11-03 15:10:57.219+08 0x00004658 INFO : file offset: 4477 [console.cpp,153 main
2023-11-03 15:10:57.243+08 0x00004658 INFO : file offset: 7935 [console.cpp,157 main
```
![image](https://github.com/chronoxor/CppCommon/assets/5846696/0d9a5cd6-22c0-4d73-922c-20e4fcf4a148)
Thie file size is 4477 bytes.
When read 1024 bytes, 4477 bytes were read into the 8K buffer, offset is 4477, it's the file end position.
When write "@@@@@" and flush, 4477-1024+5=3458 bytes were written, the new offset is 4477+3458=7935.
The remain read buffer is also written.
To avoid the problem, Seek should be called before Write, but documention doesn't say that.
Maybe Read and Write should use diffrent buffers?
```

**Comment by chronoxor** [comment]
Fixed, thanks for reporting!
