### ISSUE TITLE
Request: Compile-Time/Constexpr UUID with literal operator

### ISSUE THREAD

**Issue by uniflare** [chronoxor/CppCommon#31]
I think this would make the UUID class quite a bit more useful.
I think it should not be difficult to create a constexpr constructor for the UUID type, as well as a string literal operator function to convert a well-defined uuid string into a UUID data structure.

**Comment by chronoxor** [comment]
Implemented in [1.0.4.1](https://github.com/chronoxor/CppCommon/releases/tag/1.0.4.1)

**Comment by uniflare** [comment]
Awesome stuff 💯
