### ISSUE TITLE
Add git TAGs to help versioning

### ISSUE THREAD

**Issue by tarc** [chronoxor/CppCommon#4]
It'll be very helpful if some versioning scheme is added.

In our present use case, just some git tags would suffice.

btw, great work you're doing here!

**Comment by tarc** [comment]
Actually, I see now a `common/versio.h`:

https://github.com/chronoxor/CppCommon/blob/14389894e05fe0ca6e6446b209c6d49ec30d063d/include/common/version.h#L31-L32

But what would help us here even more is a git tag to help automate building and packaging this library for our projects.

**Comment by chronoxor** [comment]
Will do tagging

**Comment by chronoxor** [comment]
Fixed
